name: Django CI
run-name: ${{ github.actor }} is testing out GinHub Actions
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12']

    steps:
    - name: Chteckout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate
      env:
        SECRET_KEY: test-key-123
        DEBUG: "True"

    - name: Run tests
      run: |
        python manage.py test
      env:
        SECRET_KEY: test-key-123
        DEBUG: "True"